# Generated by Django 3.0.5 on 2023-02-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='upload_image',
        ),
    ]
