# Generated by Django 3.0.5 on 2023-02-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_date', models.DateField()),
            ],
        ),
    ]
