# Generated by Django 3.0.5 on 2023-02-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0005_application_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='department',
        ),
    ]
