# Generated by Django 3.0.5 on 2023-02-28 20:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0005_application_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='Application',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
