# Generated by Django 3.0.5 on 2023-02-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0006_remove_application_department'),
        ('requisition', '0007_auto_20230228_2350'),
    ]

    operations = [
    ]
