# Generated by Django 3.1.14 on 2023-03-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0014_auto_20230319_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
