# Generated by Django 3.2.18 on 2023-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0016_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
