# Generated by Django 3.2.18 on 2023-03-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0020_remove_application_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
