# Generated by Django 3.0.5 on 2023-02-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
